/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  // samples: {
  //   // Features: ["mdx"],
  //   "React 基础示例": [],
  // },
  css_tutorials: [
    // "css/css-tutorial-intro",
    // {
    //   基础: ["css/basic/css-intro"],
    //   进阶: ["css/advanced/box-model"],
    // },
    {
      type: "autogenerated",
      dirName: "css",
    },
  ],
  videos: {
    简介: ["videos/videos-intro"],
    JavaScript: ["videos/js/event-loop/event-loop"],
    CSS: [
      "videos/css/03-5-tips-master-css/5-tips-master-css",
      "videos/css/grid-layout/grid-layout",
      "videos/css/flex-layout/flex-layout",
      "videos/css/selectors/css-selectors",
      "videos/css/position/css-position",
      "videos/css/css-hsl-color/css-hsl-color",
      "videos/css/css-grid-place-items/css-grid-place-items",
      "videos/css/css-text-image-wrap/css-text-image-wrap",
      "videos/css/css-flex-gap-tutorial/css-flex-gap-tutorial",
      "videos/css/css-counter-state-management/css-counter-state-management",
      "videos/css/css-conic-gradient-tutorial/css-conic-gradient-tutorial",
      "videos/css/css-container-queries-intro/css-container-queries-intro",
      "videos/css/css-common-properties/css-common-properties",
      "videos/css/css-transition-keyframes-intro/css-transition-keyframes-intro",
    ],

    HTML: ["videos/html/html-basics/html-basics"],
    实战项目: [
      "videos/projects/html-css-full-website-idustrial/html-css-full-website-idustrial",
    ],
    特效: [
      "videos/effects/glassmorphism/effects-glassmorphism",
      "videos/effects/cyberpunk/effects-glitch",
      "videos/effects/resize/effects-resizable",
      "videos/effects/gradient-animation/gradient-animation",
      "videos/effects/js-horizontal-scroll-effect/js-horizontal-scroll-effect",
    ],
    浏览器: [
      "videos/browser/dom/what-is-dom",
      "videos/browser/bom/what-is-bom",
      "videos/browser/js-dom/js-dom-operation",
      "videos/browser/native-drag-drop/native-drag-drop",
      "videos/browser/web-components-get-started/web-components-get-started",
      "videos/browser/js-web-animations-api/js-web-animations-api",
    ],
    Web: [],
    网络: [
      "videos/network/http-basics/http-basics",
      "videos/network/https-basics/https-basics",
    ],
    React: [
      "videos/react/react-props-buttons/react-props-button",
      "videos/react/gradient-bg-react-state-event/react-state-event-gradient",
      "videos/react/03-5-react-spring-animations/5-react-spring-animations",
      "videos/react/react-docusaurus-blog-list-view/react-docusaurus-blog-list-view",
    ],
    Vue: [
      "videos/vue/vue-todo-app/vue-todo-app",
      "videos/vue/vite-get-started/vite-get-started",
      "videos/vue/vue-watch-api-tips/vue-watch-api-tips",
      "videos/vue/vue-echarts-integration/vue-echarts-integration",
      "videos/vue/vue-echarts-bar-chart/vue-echarts-bar-chart",
      "videos/vue/vue-echarts-doughnut-chart/vue-echarts-doughnut-chart",
    ],
    TypeScript: [
      "videos/ts/intro/ts-intro",
      "videos/ts/typescript-oo-basics/typescript-oo-basics",
      "videos/ts/typescript-oop-abstraction/typescript-oop-abstraction",
      "videos/ts/typescript-oop-inheritance/typescript-oop-inheritance",
      "videos/ts/typescript-oop-polymorphism/typescript-oop-polymorphism",
    ],
    Express: [
      "videos/express/express-get-started/express-get-started",
      "videos/express/express-mongo-crud/express-mongo-crud",
    ],
    "Mongo DB": ["videos/mongo/mongodb-get-started/mongodb-get-started"],
    工具: ["videos/tools/tools-vs-code-codesandbox/tools-vs-code-codesandbox"],
  },
  resources: {
    简介: ["resources/resources-intro"],
    前端开发: ["resources/ui/css-frameworks/css-frameworks"],

    开发工具: ["resources/tools/vs-code-themes/vs-code-themes"],
    效率工具: [],
    "UI 设计": [],
  },
  tools: {
    简介: ["tools/tools-intro"],
    "CSS 工具": ["tools/glassmorphism-generator/glassmorphism-generator"],
  },
};
